ERROR:root:OOPS
Traceback (most recent call last):
  File "bot/rtmbot.py", line 153, in main_loop
    bot.start()
  File "bot/rtmbot.py", line 33, in start
    for reply in self.slack_client.rtm_read():
  File "/Users/andrew/websockets2/venv/lib/python2.7/site-packages/slackclient/_client.py", line 39, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/Users/andrew/websockets2/venv/lib/python2.7/site-packages/slackclient/_server.py", line 110, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/Users/andrew/websockets2/venv/lib/python2.7/site-packages/websocket/_core.py", line 298, in recv
    opcode, data = self.recv_data()
  File "/Users/andrew/websockets2/venv/lib/python2.7/site-packages/websocket/_core.py", line 315, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/Users/andrew/websockets2/venv/lib/python2.7/site-packages/websocket/_core.py", line 328, in recv_data_frame
    frame = self.recv_frame()
  File "/Users/andrew/websockets2/venv/lib/python2.7/site-packages/websocket/_core.py", line 360, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/Users/andrew/websockets2/venv/lib/python2.7/site-packages/websocket/_abnf.py", line 312, in recv_frame
    self.recv_header()
  File "/Users/andrew/websockets2/venv/lib/python2.7/site-packages/websocket/_abnf.py", line 261, in recv_header
    header = self.recv_strict(2)
  File "/Users/andrew/websockets2/venv/lib/python2.7/site-packages/websocket/_abnf.py", line 346, in recv_strict
    bytes = self.recv(min(16384, shortage))
  File "/Users/andrew/websockets2/venv/lib/python2.7/site-packages/websocket/_core.py", line 429, in _recv
    return recv(self.sock, bufsize)
  File "/Users/andrew/websockets2/venv/lib/python2.7/site-packages/websocket/_socket.py", line 89, in recv
    raise WebSocketConnectionClosedException("Connection is already closed.")
WebSocketConnectionClosedException: Connection is already closed.
